name: Deploy Static Site

on:
  push:
    branches:
      - master  # 如果你的主分支叫 master，请修改为 master

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Inject Commit ID
        run: |
          sed -i "s/GIT_COMMIT_HASH_PLACEHOLDER/$(git rev-parse --short HEAD)/g" footer.html

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy
        uses: actions/deploy-pages@v4
